id: P010428
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:49:24.434974
source_metadata:
  id: bdr:W1KG3411
  title: མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་ཤེས་རབ་སྒྲོན་མའི་ཕྲེང་བ་སོགས་འགྲེལ་པ་ཁག་ཅིག
  author: ''
  volumes:
    07a3149e4a9b4abc8dde0097d8bd9d11:
      image_group_id: I1KG3504
      title: ''
      volume_number: 1
      total_pages: 1360
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
