id: IFEE778FA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T04:14:04+00:00'
last_modified: '2022-06-08T13:32:07.001524+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3411
  title: མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་ཤེས་རབ་སྒྲོན་མའི་ཕྲེང་བ་སོགས་འགྲེལ་པ་ཁག་ཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9333':
      image_group_id: I1KG3504
      title: ''
      total_pages: 1360
      order: 1
      base_file: 9333.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
