id: IFEE778FA
legacy_id: P010428
ocr_import_info:
  bdrc_scan_id: W1KG3411
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T04:04:49'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:05:10.729152+00:00'
last_modified: 2022-08-31 23:05:41.610177
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3411
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3411
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་ཤེས་རབ་སྒྲོན་མའི་ཕྲེང་བ་སོགས་འགྲེལ་པ་ཁག་ཅིག
  author: སློབ་དཔོན་སངས་རྒྱས་དཔལ་ཡེ་ཤེས།
statistics:
  ocr_word_mean_confidence_index: 0.8976687695980986
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG3504:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3504
      total_pages: 1360
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3504.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8976687695980986
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
